### ISSUE TITLE
Input Field with Label has no border

### ISSUE THREAD

**Issue by dippa-1** [mdbootstrap/mdb-angular-ui-kit#1]
I have the following html-code:

```html
<div class="d-flex">
    <input type="number" id="myInput" class="form-control"">
    <label for="myInput" class="form-label">Input Label</label>
</div>
```

Without a label, there is a border but with label the border disappears.
I have read that I need to insert this code:

```javascript
document.querySelectorAll('.form-outline').forEach((formOutline) => {
    new mdb.Input(formOutline).init();
})
```

But this is not the angular way of coding and mdb.Input doesn't even exist.

So how can I initialize a mdb Input with Angular?

**Comment by idzark** [comment]
Here is an example of Angular syntax:

```
<mdb-form-control>
  <input mdbInput type="text" id="form1" class="form-control" />
  <label mdbLabel class="form-label" for="form1">Example label</label>
</mdb-form-control>
```

The component will be initialized automatically when you use this code.

**Comment by dippa-1** [comment]
Thanks, it works.
I didn't know that I have to use tags like <mdb-form-control> and <input mdbInput ...>
In the mdb angular docs it looks like you only need the bootstrap classes and no material design specific tags/directives.
