### ISSUE TITLE
Hamburger animation doc not available for angular in mdb bootstrap 4

### ISSUE THREAD

**Issue by tushar33** [mdbootstrap/mdb-angular-ui-kit#151]
Using `<mdb-navbar><mdb-navbar/>"` for navigation but didn't found angular document to do open close animation for hamburger menu.

I need to apply below animations
https://mdbootstrap.com/snippets/jquery/mdbootstrap/911054

**Comment by idzark** [comment]
Unfortunately, we don't have this animation for the MDBA4 navbar, we currently don't have plans to add such a feature for this component.

**Comment by tushar33** [comment]
@idzark Thanks for the update.
