### ISSUE TITLE
Dropdown menu can't be navigated with arrow key

### ISSUE THREAD

**Issue by hghammoud** [mdbootstrap/mdb-angular-ui-kit#152]
Expected behavior 
The examples in the docs work perfectly. Upon showing a dropdown menu i can use arrow keys to navigate the menu items

Actual behavior 
I downloaded the started kit "MDB5-ANGULAR-UI-KIT-Free" and replaced the app.component.html content with an example from the docs.The dropdown shows but I can not use the arrow keys to select. 

Any idea how to solve that? in bootstrap 5 it works and your demo site also.

**Comment by idzark** [comment]
@hghammoud We have fixed that in v2.2.0, please upgrade your version and let us know if that helped.

**Comment by hghammoud** [comment]
Thank you ill be giving it a test
