### ISSUE TITLE
Cannot upgrade to Angular v14 due to package dependency on @angular/cdk v13

### ISSUE THREAD

**Issue by waynegakuo** [mdbootstrap/mdb-angular-ui-kit#153]
Currently, if one has an Angular v13 app with angular-bootstrap-md v13, they will not be able to update their Angular apps to v14 due to the package's dependency on @angular/cdk v13. Is there a new version that's to be rolled out soon?
cc: @idzark 

` Package "angular-bootstrap-md" has an incompatible peer dependency to "@angular/cdk" (requires "^13.0.0", would install "14.0.1").`

**Comment by idzark** [comment]
@waynegakuo We haven't released a new version with support for Angular 14 yet. It should be available in the near future but we can't provide an ETA yet.

**Comment by waynegakuo** [comment]
Awesome. Thank you, @idzark

**Comment by Prinzpoupou** [comment]
Hi is there any updates on this?

**Comment by mraible** [comment]
I'm interested in this as well since JHipster 7 now uses Angular 14. I'm trying to update my [JHipster Mini-Book](https://www.infoq.com/minibooks/jhipster-mini-book-5/) to show how to use this library.

**Comment by Lumpenstein** [comment]
Also looking forward for the @14 version. Still no ETA available ?

**Comment by WeslleyDeSouza** [comment]
14 is now available

**Comment by mraible** [comment]
I found that I was able to do the following with the previous version:

```
npm i mdb-angular-ui-kit
```

With the latest version, I have to do the following:

```
npm i mdb-angular-ui-kit @angular/cdk
```

Is this expected?

**Comment by idzark** [comment]
@mraible Please make sure to update all Angular dependencies to v14 before installing MDB Angular v3. In case of any further problems please consider creating a new issue and provide more details about the errors.
