### ISSUE TITLE
Not working fade animation in tabs

### ISSUE THREAD

**Issue by shmasya** [mdbootstrap/mdb-angular-ui-kit#154]
I can't understand why tabs don't switch smoothly, as in your Demo on the site?

https://stackblitz.com/edit/angular-ivy-tecpyx?file=src/app/app.component.html

**Comment by idzark** [comment]
@shmasya Thank you for reporting this problem, it looks like there is a bug in the mdb-tabs component. We will take a closer look at that and add a fix in an upcoming release.

**Comment by idzark** [comment]
This problem was fixed in v3.0.0
