### ISSUE TITLE
Dont work to Angular 15

### ISSUE THREAD

**Issue by carlosptt** [mdbootstrap/mdb-angular-ui-kit#157]
Hi you library dont work for Angular 15 any update?

**Comment by idzark** [comment]
@carlosptt We plan to release a new version with support for Angular 15 later this month (probably within two weeks), but we can't provide an exact date yet.

**Comment by akhilgro** [comment]
Any Update on the release of angular 15 supported mdb

**Comment by waynegakuo** [comment]
Hello @idzark 
Any update on the support for Angular v15 and probable dates?

**Comment by idzark** [comment]
The new version with support for Angular 15 will be available next Monday (09.01)

**Comment by idzark** [comment]
The new (4.0.0) version is now available
