### ISSUE TITLE
Bug with the class "modal-dialog-scrollable"

### ISSUE THREAD

**Issue by JoniJnm** [mdbootstrap/mdb-angular-ui-kit#160]
When the modal has the class "modal-dialog-scrollable" there is a bug, a scrollbar appears:

![image](https://user-images.githubusercontent.com/577282/213265031-07173c4d-f262-4977-8bbb-904c8e78e6da.png)

I created a stackblitz and github repo where reproduce the problem:

* https://stackblitz.com/edit/mdboostrap-modal-bug
* https://github.com/JoniJnm/mdboostrap-modal-bug

The problem occurs due margin & height values.

**Comment by idzark** [comment]
Thank you. I added this to our to-do list and it should be fixed in the next update.

**Comment by idzark** [comment]
We added a fix for this bug in v4.1.0. Please update your MDB version and let us know if you encounter any further problems.
