### ISSUE TITLE
Bug with sidenav and slim

### ISSUE THREAD

**Issue by JoniJnm** [mdbootstrap/mdb-angular-ui-kit#161]
This example: https://mdbootstrap.com/docs/angular/navigation/sidenav/#section-sidenav-slim is bugged in a real angular version (problem collapsing the menu after turn off/on the slim mode).

How can I create a repository where reproduce the problem? The sidenav component is not free. I want to create an issue similar as https://github.com/mdbootstrap/mdb-angular-ui-kit/issues/160

**Comment by idzark** [comment]
Could you please provide some more information about the bug and reproduction steps? 

If you have access to the side nav component, you could just create a repository with the component code and not include the MDB tgz file or your private token. We will be able to use this code to reproduce the problem.

**Comment by JoniJnm** [comment]
I couldn't reproduce the problem in ui-kit 4.0
