### ISSUE TITLE
Angular 16 Support Release Date?

### ISSUE THREAD

**Issue by xinthose** [mdbootstrap/mdb-angular-ui-kit#162]

**Comment by idzark** [comment]
We can't provide an ETA yet. We will try to add support for v16 as soon as possible, but we still need some time to test the changes from the new Angular version and to add changes to our own code.

**Comment by idzark** [comment]
@xinthose The new v5.0.0 release with support for Angular 16 is now available.

**Comment by xinthose** [comment]
@idzark OK.  Thank you.
