### ISSUE TITLE
Replace license.pdf with a text file

### ISSUE THREAD

**Issue by cschaible** [mdbootstrap/mdb-angular-ui-kit#2]
Hi, there's a PDF file in the published artifact. This increases the artifact size and pollutes the automatically generated 3rdpartylicenses.txt file provided by angular. 

Could you please replace the PDF with a normal license file like [this](https://github.com/angular/angular/blob/master/LICENSE).

It's in the [mdb-angular-ui-kit/projects/mdb-angular-ui-kit/](https://github.com/mdbootstrap/mdb-angular-ui-kit/tree/master/projects/mdb-angular-ui-kit) directory.

Thanks in advance!

Regards Christian

**Comment by idzark** [comment]
We replaced the PDF file inside the library directory, we will also fix that in the npm package in the next update.

Thank you for alerting us to this problem.
